env: "local"
pg_dsn: "host=localhost port=6432 dbname=url-shortener user=url-shortener-user password=1234 sslmode=disable"
http_server:
  address: "localhost:8000"
  timeout: 4s
  idle_timeout: 60s
  user: "Aleks"
  password: "1234"